[build]
builder = "paketobuildpacks/builder:base"

[deploy]
# Go inside backend, build a jar, and run it
start = "cd backend && ./mvnw clean package -DskipTests && java -jar target/*.jar"

[env]
PORT = "5000"

